[package]

name = "piston-ai_behavior"
version = "0.0.4"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>"
]
keywords = ["ai", "behavior", "piston", "game", "logic"]
description = "AI behavior tree"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/ai_behavior.git"
homepage = "https://github.com/pistondevelopers/ai_behavior"

[lib]

name = "ai_behavior"
path = "src/lib.rs"

[dependencies.piston]
git = "https://github.com/PistonDevelopers/piston"
#version = "0.1.0"

[dependencies]

rustc-serialize = "*"
num = "0.1.21"

[[test]]

name = "tests"
